

#ifndef	__BCDSEVSEGMENT_CFG_H__
#define __BCDSEVSEGMENT_CFG_H__

#define BCDSEVSEGMENTS_DATA_PIN_0 8
#define BCDSEVSEGMENTS_DATA_PIN_1 9
#define BCDSEVSEGMENTS_DATA_PIN_2 10
#define BCDSEVSEGMENTS_DATA_PIN_3 11

#define BCDSEVSEGMENTS_D_Enable_PIN 26
#define BCDSEVSEGMENTS_C_Enable_PIN 27
#define BCDSEVSEGMENTS_B_Enable_PIN 30
#define BCDSEVSEGMENTS_A_Enable_PIN 31


#endif

